version: '3.4'

services:
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    container_name: kafka-cluster
    environment:
      - ADV_HOST=127.0.0.1
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
